apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
#  minReadySeconds: 30
  replicas: 2
  selector: # use selector to decide which pod definition is part of replicaset
    matchLabels:
      app: webapp
  template: #template for pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5