apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec: #job
  template:
    spec: #pod spec, wrapped in job spec
      containers:
      - name: long-job
        image: python
        command: ["python"]
        args: ["-c", "import time; print('starting'); time.sleep(30); print('done!')"]
      restartPolicy: Never # otherwise, defaulted to Always restart
  backoffLimit: 2 #if job fails, restart x times